[package]
name = "fastn-automerge"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
automerge.workspace = true
autosurgeon.workspace = true
rusqlite.workspace = true