[package]
name = "fastn-automerge"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "fastn-automerge"
path = "src/main.rs"

[dependencies]
automerge.workspace = true
autosurgeon.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
clap.workspace = true
eyre.workspace = true
fastn-automerge-derive.workspace = true
fastn-id52 = { workspace = true, features = ["automerge"] }

[dev-dependencies]
tempfile = "3"