[package]
name = "fastn-automerge"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Core dependencies
automerge.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
eyre.workspace = true
tracing.workspace = true
chrono.workspace = true