[package]
name = "fastn-id52"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
description = "fastn ID52 identity and cryptographic key management"
homepage.workspace = true
license.workspace = true

[[bin]]
name = "fastn-id52"
path = "src/main.rs"

[dependencies]
ed25519-dalek.workspace = true
data-encoding.workspace = true
serde.workspace = true
rand.workspace = true
keyring.workspace = true

# Optional DNS lookup support
tokio = { workspace = true, optional = true, features = ["rt"] }
hickory-resolver = { version = "0.24", optional = true }

# Optional autosurgeon support
autosurgeon = { workspace = true, optional = true }
automerge = { workspace = true, optional = true }

[features]
dns = ["dep:tokio", "dep:hickory-resolver"]
automerge = ["dep:autosurgeon", "dep:automerge"]
