[package]
name = "fastn-mail"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "SMTP and IMAP implementation for fastn p2p email"

[[bin]]
name = "fastn-mail"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = ["clap", "tracing-subscriber"]

[dependencies]
automerge.workspace = true
autosurgeon.workspace = true
chrono.workspace = true
eyre.workspace = true
fastn-automerge.workspace = true
fastn-id52 = { workspace = true, features = ["automerge"] }
futures.workspace = true
regex.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
mail-parser = "0.9"

# CLI dependencies (optional)
clap = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
