[package]
name = "fastn-mail"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Core dependencies
fastn-automerge.workspace = true
autosurgeon.workspace = true
automerge.workspace = true
fastn-id52 = { workspace = true, features = ["automerge"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true

# For database storage
rusqlite.workspace = true

# For timestamps
chrono.workspace = true

# For email parsing
mail-parser = "0.9"