[package]
name = "fastn-compiler"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
fastn-builtins.workspace = true
fastn-resolved.workspace = true
fastn-continuation.workspace = true
fastn-package.workspace = true
fastn-section.workspace = true
fastn-unresolved.workspace = true
indexmap.workspace = true
tracing.workspace = true
