<Document> ::= <CommentOrEmptyLine>* <ModuleDoc>? (<Comment> | <EmptyLine> | <Section>)*;

<ModuleDoc> ::= <DocComment>

<DocComment> ::= <DocCommentLine>+
<DocCommentLine> ::= ";-;" <AnyCharacterExceptNewline>* <Newline>
<Comment> ::= <CommentLine>+
<CommentLine> ::= ";;" <AnyCharacterExceptNewline>* <Newline>

<CommentOrEmptyLine> ::= <Comment> | <EmptyLine>

<Section> ::= <Space>? '--' <Space>? <KindedName> <Space>? '()'? <Space>? ':' <HeaderValue>

<HeaderValue> ::= <Tes>* '\n'

<Tes> ::= <Text> | <Expression> | <InlineSection>
<Text> ::= (<AnyCharacterExcept '{' or '}'>)+
<Expression> ::= '{' <Tes>* '}' | '${' <Tes>* '}'
<InlineSection> ::= '{--' <Space>? <SectionContent> '}'
<SectionContent> ::= <Identifier> [':' <Tes>*] [<Headers>] [<Body>]


<KindedName> ::= <Kind>? <Name>

<Name> ::= <Word>

<Kind> ::= <Word> <Space>* ('<' <WhiteSpace>? <Kind> <WhiteSpace>?  '>')?

<EscapedComment> ::= "\\;;"
<EscapedDocComment> ::= "\\;-;"
<DashDash> ::= "--"
<Word> ::= <NonWhitespaceCharacter>+
<FunctionMarker> ::= "(" <SpaceCharacter>* ")"
<Colon> ::= ":"
<EscapedDollarCurly> ::= "\\${"
<DollarCurly> ::= "${"
<Curly> ::= "{"
<CurlyClose> ::= "}"
<DollarSquare> ::= "$["
<DoubleDollarSquare> ::= "$$["
<EscapedDollarSquare> ::= "\\$["
<EscapedDoubleDollarSquare> ::= "\\$$["

<AnyCharacterExceptNewline> ::= 'a-zA-Z0-9'  // this is not real
<NonWhitespaceCharacter>    ::= 'a-zA-Z0-9'  // this is not real

<WhiteSpace> ::= (<Space> | <Newline>)+

<Space> ::= <SpaceCharacter>+
<EmptyLine> ::= <SpaceCharacter>* <Newline>
<Newline> ::= '\n'