[package]
name = "fastn-account"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Core dependencies
fastn-id52 = { workspace = true, features = ["automerge"] }
fastn-automerge.workspace = true
fastn-mail.workspace = true
fastn-router.workspace = true
fastn-fbr.workspace = true
autosurgeon.workspace = true

# Include directory for embedded fastn-home content
include_dir = "0.7"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true

# For Automerge documents
automerge.workspace = true

# For database storage
rusqlite.workspace = true

# For password hashing
argon2.workspace = true
rand.workspace = true

# For timestamps
chrono.workspace = true