[package]
name = "fastn-entity"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Entity management for fastn P2P network"
homepage.workspace = true
license.workspace = true

[dependencies]
fastn-id52 = { path = "../fastn-id52", version = "0.1.1" }
eyre.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true