// Document path constructors are now auto-generated by #[derive(Document)]:

// Re-export mail automerge documents from fastn-mail
pub use fastn_mail::DefaultMail;

#[derive(
    Debug,
    Clone,
    PartialEq,
    serde::Serialize,
    fastn_automerge::Reconcile,
    fastn_automerge::Hydrate,
    fastn_automerge::Document,
)]
#[document_path("/-/aliases/{id52}/readme")]
pub struct AliasReadme {
    /// The alias public key (for document ID)
    #[document_id52]
    pub alias: fastn_id52::PublicKey,
    /// Display name for this alias (optional)
    pub name: Option<String>,
    /// Bio or description (optional)
    pub bio: Option<String>,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    serde::Serialize,
    fastn_automerge::Reconcile,
    fastn_automerge::Hydrate,
    fastn_automerge::Document,
)]
#[document_path("/-/aliases/{id52}/notes")]
pub struct AliasNotes {
    /// The alias public key (for document ID)
    #[document_id52]
    pub alias: fastn_id52::PublicKey,
    /// Nickname or short name for this alias (optional)
    pub nickname: Option<String>,
    /// Private notes about this alias (optional)
    pub notes: Option<String>,
    /// Unix timestamp when this alias became part of our relationships
    pub relationship_started_at: i64,
}
