// Document path constructors are now auto-generated by the derive macro:
// - rig_config_path() for RigConfig
// - entity_status_path() for EntityStatus

#[derive(
    Debug,
    Clone,
    PartialEq,
    serde::Serialize,
    fastn_automerge::Reconcile,
    fastn_automerge::Hydrate,
    fastn_automerge::Document,
)]
#[document_path("/-/rig/{id52}/config")]
pub struct RigConfig {
    /// The rig's own public key (for document ID)
    #[document_id52]
    pub rig: fastn_id52::PublicKey,
    /// The rig owner's public key (who controls this rig)
    pub owner: fastn_id52::PublicKey,
    /// Unix timestamp when the rig was created
    pub created_at: i64,
    /// The current active entity
    pub current_entity: fastn_id52::PublicKey,
}

// Additional methods for RigConfig beyond basic CRUD
impl RigConfig {
    pub fn update_current_entity(
        db: &fastn_automerge::Db,
        rig_id52: &fastn_id52::PublicKey,
        entity: &fastn_id52::PublicKey,
    ) -> eyre::Result<()> {
        // Use derive macro pattern instead of deprecated modify
        let mut config = Self::load(db, rig_id52)?;
        config.current_entity = *entity;
        Ok(config.update(db)?)
    }

    pub fn get_current_entity(
        db: &fastn_automerge::Db,
        rig_id52: &fastn_id52::PublicKey,
    ) -> eyre::Result<fastn_id52::PublicKey> {
        let config = Self::load(db, rig_id52)?;
        Ok(config.current_entity)
    }
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    serde::Serialize,
    fastn_automerge::Reconcile,
    fastn_automerge::Hydrate,
    fastn_automerge::Document,
)]
#[document_path("/-/entities/{id52}/status")]
pub struct EntityStatus {
    /// The entity's public key (for document ID)
    #[document_id52]
    pub entity: fastn_id52::PublicKey,
    /// Whether the entity is currently online
    pub is_online: bool,
    /// Unix timestamp when the status was last updated
    pub updated_at: i64,
}

// Additional methods for EntityStatus beyond basic CRUD
impl EntityStatus {
    pub fn is_online(
        db: &fastn_automerge::Db,
        entity_id52: &fastn_id52::PublicKey,
    ) -> eyre::Result<bool> {
        match Self::load(db, entity_id52) {
            Ok(status) => Ok(status.is_online),
            Err(_) => Ok(false), // Default to offline if document doesn't exist
        }
    }

    pub fn set_online(
        db: &fastn_automerge::Db,
        entity_id52: &fastn_id52::PublicKey,
        online: bool,
    ) -> eyre::Result<()> {
        // Load existing document (strict - must exist)
        let mut status = Self::load(db, entity_id52)?;

        // Update status
        status.is_online = online;
        status.updated_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64;

        // Save updated document
        Ok(status.save(db)?)
    }
}
