[package]
name = "fastn-resolved"
version = "0.1.1"
#authors.workspace = true
edition = "2021"
#description.workspace = true
license = "BSD-3-Clause"
#repository.workspace = true
#homepage.workspace = true

[features]
owned-tdoc = []

[dependencies]
serde = "1"
indexmap = "2"
