[package]
name = "fastn-p2p"
version = "0.1.0"
edition.workspace = true
description = "High-level, type-safe P2P communication for fastn"
homepage.workspace = true
license.workspace = true

[dependencies]
fastn-net = { path = "../fastn-net", version = "0.1.2" }
fastn-id52 = { path = "../fastn-id52", version = "0.1.1" }
async-stream.workspace = true
eyre.workspace = true
futures-core.workspace = true
futures-util.workspace = true
iroh.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

# Re-export proc macros from separate crate
fastn-p2p-macros = { path = "../fastn-p2p-macros", version = "0.1.0" }

[dev-dependencies]
tokio-test = "0.4"
enum-display-derive = "0.1"