[package]
name = "fastn-ascii-renderer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "ASCII rendering engine for FTD components"
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
taffy = "0.5"
ansi_term = "0.12"
unicode-width = "0.2"

[dev-dependencies]