[package]
name = "fastn-ascii-renderer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "ASCII rendering engine for FTD components"
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
# Core rendering
taffy = "0.5"
ansi_term = "0.12"
unicode-width = "0.2"

# Spec viewer TUI (optional)
ratatui = { version = "0.28", optional = true }
crossterm = { version = "0.27", optional = true }
notify = { version = "6.1", optional = true }
walkdir = { version = "2.4", optional = true }
syntect = { version = "5.1", optional = true }
once_cell = { version = "1.19", optional = true }
clap = { version = "4", features = ["derive"], optional = true }

[features]
default = ["spec-viewer"]
spec-viewer = ["ratatui", "crossterm", "notify", "syntect", "walkdir", "once_cell", "clap"]

[[bin]]
name = "spec-viewer"
path = "src/bin/spec_viewer.rs"

[dev-dependencies]