[package]
name = "fastn-fbr"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# HTTP types
fastn-router.workspace = true

# File system operations
tokio.workspace = true

# Error handling
thiserror.workspace = true

# Template engine (Django-style for Rust)
tera = "1"

# Async trait support
async-trait.workspace = true

# Serialization for template context
serde.workspace = true
serde_json.workspace = true

# Time handling for templates
chrono.workspace = true

# Logging
tracing.workspace = true