[package]
name = "fastn-fbr"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# HTTP types
fastn-router.workspace = true

# File system operations
tokio.workspace = true

# Error handling
thiserror.workspace = true

# HTML escaping for templates
html-escape = "0.2"

# Logging
tracing.workspace = true