# https://github.com/calibreapp/image-actions
name: Optimize Images
on:
  push:
    branches:
      - main
    paths:
      - 'fastn.com/**.jpg'
      - 'fastn.com/**.jpeg'
      - 'fastn.com/**.png'
      - 'fastn.com/**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true # don't make a commit!
          ignorePaths: 'fastn-core/**'
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
